spring:
  datasource:
    postgres-db:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/RentCarSpring#2
      username: postgres
      password: 'Zhad02iv'
      enabled: true
      pool-size: 15
  liquibase:
    enabled: true
    change-log: classpath:/config/changelog-master.xml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  springdoc:
    api-docs:
      path: /api-docs
    override-with-generic-response: false

